package newmscwebsite

public enum CLTPosition {
	CHAIR, HIKE, IT, COMMUNITY_RELATIONS, RESEARCH, CONSTRUCTION_AND_MAINTENANCE,
	NATURE_GUIDES, PARTNERSHIP_DEVELOPMENT, VOLUNTEER_SUPPORT, PATROL, PATHFINDERS

}
